// <auto-generated />
namespace FinalPractice.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201707240704595_UserFieldAdding1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201707240704595_UserFieldAdding1));
        
        string IMigrationMetadata.Id
        {
            get { return "201707250811075_201707240704595_UserFieldAdding1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
